### ISSUE TITLE
String Reference not set to an instance of a String (Parameter 's')

### ISSUE THREAD

**Issue by edwinn1990** [stimulsoft/Samples-Angular#2]
Hi there

Please download  sample project from the link below  that reproduce this issue 

![image](https://user-images.githubusercontent.com/43356559/98197855-27def780-1f84-11eb-888a-8381e0097689.png)

https://drive.google.com/file/d/1Ljhsqx0ZBH2gimOaO377sv7uSHOkc9fw/view?usp=sharing

Thanks

**Comment by VadimMatveev** [comment]
Hello @edwinn1990 

Your link is inaccessible

**Comment by edwinn1990** [comment]
> Hello @edwinn1990
> 
> Your link is inaccessible

Hi 

Please try now

**Comment by edwinn1990** [comment]
A

> Hi there
> 
> Please download sample project from the link below that reproduce this issue
> 
> ![image](https://user-images.githubusercontent.com/43356559/98197855-27def780-1f84-11eb-888a-8381e0097689.png)
> 
> https://drive.google.com/file/d/1Ljhsqx0ZBH2gimOaO377sv7uSHOkc9fw/view?usp=sharing
> 
> Thanks

Anu Update on this issue ?

Thanks

**Comment by VadimMatveev** [comment]
Hello, @edwinn1990

We need time to prepare answer for you

**Comment by VadimMatveev** [comment]
Hello, @edwinn1990 
Hello.

For stimulsoft-viewer-angular component you should use [requestUrl] like: https://localhost:44375/Viewer/{action}   (like in samples)
instead of https://localhost:44375/Viewer/InitViewer

**Comment by edwinn1990** [comment]
Hi

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by edwinn1990** [comment]
still does not work ...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by VadimMatveev** [comment]
Hello, @edwinn1990

For stimulsoft-viewer-angular component you should use [requestUrl] like: https://localhost:44375/Viewer/{action} (like in samples)
instead of https://localhost:44375/Viewer/InitViewer
